language: go
go:
  - 1.8.1
services:
  - docker
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
install:
  - go get github.com/Masterminds/glide
  - glide install --strip-vendor
  - make